name: Serve

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - master
      - beta-releases
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Setup dependencies
        run: |
          npm i -g @ionic/cli
          npm i
          
      - name: Serve
        run: ionic serve
